version: '3.8'
services:
  backend:
    image: security:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres
      - DB_HOST = database
  database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=postgres'
    ports:
      - '5436:5432'
